#include <backend/executeable_path.hpp>
#include <backend/filesystem.hpp>

#include <nui/backend/rpc_hub.hpp>
#include <nui/core.hpp>
#include <nui/window.hpp>

#include <nui/backend/filesystem/file_dialog.hpp>
#include <portable-file-dialogs.h>

// This file is generated by nui and the header name is the target name
#include <index.hpp>

#include <filesystem>
#include <iostream>
#include <string>

int main(int argc, char** argv)
{
    using namespace Nui;
    using namespace std::string_literals;

    // Set verbosity to true
    pfd::settings::verbose(true);

    // const auto result = FileDialog::showOpenDialog({.title = "Hi"});

    Window window{"Minecraft Modpack Maker", true /* may open debug window */};
    window.setSize(1200, 800, WebViewHint::WEBVIEW_HINT_NONE);
    window.setHtml(index());
    // window.navigate(
    //     "file://"s +
    //     (getExecuteablePath().parent_path().parent_path() / "module_minecraft-modpack-maker" / "bin" / "index.html")
    //         .string());

    window.setVirtualHostNameToFolderMapping(
        "local",
        (getExecuteablePath().parent_path().parent_path() / "module_minecraft-modpack-maker" / "bin").string(),
        HostResourceAccessKind::Allow);

    RpcHub hub{window};
    FileSystem::registerAll(hub);
    hub.enableAll();
    window.run();
}